### ISSUE TITLE
NPE when calling PlayerHeadsAPI:getHeadFrom( blank playerhead item )

### ISSUE THREAD

**Issue by crashdemons** [crashdemons/PlayerHeads#52]
```
[08.01 15:21:50] [Server] java.lang.IllegalArgumentExceptionConstructing from null Profile
[08.01 15:21:50] [Server] 	at com.github.crashdemons.playerheads.compatibility.craftbukkit.CompatibleProfileCB.<init>(CompatibleProfileCB.java:27) ~[?:?]
[08.01 15:21:50] [Server] 	at com.github.crashdemons.playerheads.compatibility.craftbukkit.ProfileUtils.getProfile(ProfileUtils.java:46) ~[?:?]
[08.01 15:21:50] [Server] 	at com.github.crashdemons.playerheads.compatibility.craftbukkit_1_13.Provider_craftbukkit_113.getOwningPlayer(Provider_craftbukkit_113.java:40) ~[?:?]
[08.01 15:21:50] [Server] 	at com.github.crashdemons.playerheads.SkullConverter.skullTypeFromItemStack(SkullConverter.java:109) ~[?:?]
[08.01 15:21:50] [Server] 	at com.github.crashdemons.playerheads.api.ApiProvider.getHeadFrom(ApiProvider.java:47) ~[?:?]
[08.01 15:21:50] [Server] 	at com.github.crashdemons.trophyrecipes.integrations.PlayerHeadsSupport.identifyHeadType(PlayerHeadsSupport.java:116) ~[?:?]
```

**Comment by crashdemons** [comment]
appears to be fixed with the second change
although would have preferred CompatibilityProviders to check for null instead of giving them a dummy profile.
